### ISSUE TITLE
Percent encode incorrect

### ISSUE THREAD

**Issue by drozzy** [gmr/urilib#2]
According to RFC3986 if we encode "Ladies + Gentlemen"

Expected is: "Ladies%20%2B%20Gentlemen"
Produced is: "Ladies%20%2b%20Gentlemen"

See: https://dev.twitter.com/oauth/overview/percent-encoding-parameters

**Comment by gmr** [comment]
In digging in to RFC-3986 @ https://www.ietf.org/rfc/rfc3986.txt, section 2.1:

>  The uppercase hexadecimal digits 'A' through 'F' are equivalent to
>  the lowercase digits 'a' through 'f', respectively.  If two URIs
>  differ only in the case of hexadecimal digits used in percent-encoded
>   octets, they are equivalent.  For consistency, URI producers and
>   normalizers should use uppercase hexadecimal digits for all percent-
>  encodings.

That being said, I've run into issues with some servers/APIs behaving badly with regard to this.  Perhaps having something to differentiate in the API requiring upper-case hex vs lower-case hex would be useful.

**Comment by gmr** [comment]
I've added two new methods:
- `pecent_encode/2`
- `plus_encode/2`

Where you can explicitly invoke which case you want hex values to be returned as:

``` erlang
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.1  (abort with ^G)
1> urilib:percent_encode("/✈this is än êxample value woot✈/", uppercase).
"%2F%C0%88this%20is%20%C3%A4n%20%C3%AAxample%20value%20woot%C0%88%2F"
```

and have uploaded the new version to hex as 0.2.0.
